# Numpy

In [ ]:
import numpy as np

In [2]:
a= np.array(range(10))

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
type(a)

numpy.ndarray

### 배열 생성
- 기본
- arr_obj = np.array(seq_data)

In [5]:
l1 = [5,4,8,10]
b = np.array(l1)
b

array([ 5,  4,  8, 10])

In [6]:
arr1 = range(10)
arr1

range(0, 10)

In [7]:
l2 = [1,2,3,4,'a']
c = np.array(l2)
c

array(['1', '2', '3', '4', 'a'], dtype='<U11')

In [8]:
l3 = [1,2.0,3.0,4.5]
d = np.array(l3)
d

array([1. , 2. , 3. , 4.5])

In [9]:
a.shape

(10,)

In [10]:
b.shape

(4,)

In [11]:
c.shape

(5,)

In [12]:
d.shape

(4,)

## 차원의 개념 


In [13]:
l1 = [[1,2],[3,4]]
a = np.array(l1)
a

array([[1, 2],
       [3, 4]])

In [14]:
a.dtype

dtype('int32')

In [15]:
a.shape

(2, 2)

In [18]:
# 행렬이 같아야 차원이 성립
# 다를 경우 성립 x
l2 = [[1,2,3],[1,2]]
b= np.array(l2)
b

array([list([1, 2, 3]), list([1, 2])], dtype=object)

In [19]:
b.shape

(2,)

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
range(10)

range(0, 10)

In [22]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [24]:
#반환만 다르고 range와 똑같이 쓰임

In [27]:
#np.linspace(start,stop[,num=50])
np.linspace(10,20,9) #start 이상 stop 미만 num 등분한 array

array([10.  , 11.25, 12.5 , 13.75, 15.  , 16.25, 17.5 , 18.75, 20.  ])

In [26]:
np.linspace(10,20) #등분은 기본적으로 50

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

### Shape

[nd 배열].reshape(newshape)

n차원 배열을 newshape 형태로 변환하여 반환한다.

만약 newshape == -1 이면 1차원 배열로 변환하여 반환한다.

[nd 배열].shape = (newshape)

n차원 배열 자체를 newshape 형태로 변환한다.

만약 newshape == -1 이면 1차원 배열로 변경한다.

>>> arr1 = np.arange(10)
>>> arr1
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

>>> arr2 = arr1.reshape(2,5)  # arr1.reshape((2,5))
>>> arr2
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

>>> arr3 = arr2.reshape(-1)
>>> arr3
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

>>> arr3.shape = (2,5)
>>> arr3
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])



In [29]:
a = np.arange(2,10)
a

array([2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a.shape

(8,)

In [31]:
b = a.reshape(2,4)

In [32]:
b

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [34]:
a.shape = (2,4)

In [35]:
a

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [36]:
a.shape = -1

In [37]:
a

array([2, 3, 4, 5, 6, 7, 8, 9])

### 배열의 데이터타입 변환
- [nd 배열].astype(dtype)
- n차원 배열의 데이터 타입을 dtype으로 변환

In [38]:
data1 = ['1.5','.62','3.14','3.141592']
str_arr = np.array(data1)
str_arr

array(['1.5', '.62', '3.14', '3.141592'], dtype='<U8')

In [39]:
float_arr = str_arr.astype(float)
float_arr

array([1.5     , 0.62    , 3.14    , 3.141592])

In [40]:
float_arr.dtype

dtype('float64')

In [46]:
temp_arr = np.linspace(10,30)
temp_arr

array([10.        , 10.40816327, 10.81632653, 11.2244898 , 11.63265306,
       12.04081633, 12.44897959, 12.85714286, 13.26530612, 13.67346939,
       14.08163265, 14.48979592, 14.89795918, 15.30612245, 15.71428571,
       16.12244898, 16.53061224, 16.93877551, 17.34693878, 17.75510204,
       18.16326531, 18.57142857, 18.97959184, 19.3877551 , 19.79591837,
       20.20408163, 20.6122449 , 21.02040816, 21.42857143, 21.83673469,
       22.24489796, 22.65306122, 23.06122449, 23.46938776, 23.87755102,
       24.28571429, 24.69387755, 25.10204082, 25.51020408, 25.91836735,
       26.32653061, 26.73469388, 27.14285714, 27.55102041, 27.95918367,
       28.36734694, 28.7755102 , 29.18367347, 29.59183673, 30.        ])

In [47]:
temp_arr.astype(int)

array([10, 10, 10, 11, 11, 12, 12, 12, 13, 13, 14, 14, 14, 15, 15, 16, 16,
       16, 17, 17, 18, 18, 18, 19, 19, 20, 20, 21, 21, 21, 22, 22, 23, 23,
       23, 24, 24, 25, 25, 25, 26, 26, 27, 27, 27, 28, 28, 29, 29, 30])

### 난수배열 생성
- np.random.rand(d0, d1, ..., dn)
 - 0과 1사이에 균일분표에서 (d0, d1, …, dn) 형태의 실수 배열을 난수생성
- np.random.randint(low[, high, size, dtype])
 - low와 high사이 정수 중 size만큼의 정수 배열을 난수생성
- np.random.randn(d0, d1, ..., dn)
 - 평균이 0 표준편차가 1인 정규분포에서 (d0, d1, …, dn) 형태의 난수생성

- linear하게 num만큼 배열 선언
 - rand_float = np.random.rand()
 - rand_float
  + 0.35426100728807075

 - rand_n_arr = np.random.randn(2,3)
 - rand_n_arr
  + array([[-0.54890223, -0.1501966 ,  0.80294757],
  +     [-0.97233412, -1.24891298, -0.32100883]])



### 인덱스

In [48]:
a = np.linspace(1,20,9)
a

array([ 1.   ,  3.375,  5.75 ,  8.125, 10.5  , 12.875, 15.25 , 17.625,
       20.   ])

In [50]:
a = a.reshape(3,3)
a

array([[ 1.   ,  3.375,  5.75 ],
       [ 8.125, 10.5  , 12.875],
       [15.25 , 17.625, 20.   ]])

In [51]:
a[1][2]

12.875

In [53]:
a[1,2] # 좀 더 빠름

12.875

In [54]:
a[1:]

array([[ 8.125, 10.5  , 12.875],
       [15.25 , 17.625, 20.   ]])

In [61]:
a[1:,:2]

array([[ 8.125, 10.5  ],
       [15.25 , 17.625]])

In [62]:
b = a.reshape(-1)

In [63]:
b

array([ 1.   ,  3.375,  5.75 ,  8.125, 10.5  , 12.875, 15.25 , 17.625,
       20.   ])

In [65]:
b[1::2] # start, stop, step

array([ 3.375,  8.125, 12.875, 17.625])

In [66]:
a

array([[ 1.   ,  3.375,  5.75 ],
       [ 8.125, 10.5  , 12.875],
       [15.25 , 17.625, 20.   ]])

In [67]:
a[::2,::2]

array([[ 1.  ,  5.75],
       [15.25, 20.  ]])

In [68]:
b

array([ 1.   ,  3.375,  5.75 ,  8.125, 10.5  , 12.875, 15.25 , 17.625,
       20.   ])

In [71]:
b[b>10]

array([10.5  , 12.875, 15.25 , 17.625, 20.   ])

In [72]:
a

array([[ 1.   ,  3.375,  5.75 ],
       [ 8.125, 10.5  , 12.875],
       [15.25 , 17.625, 20.   ]])

In [75]:
a[1, a[1]>9] # row, 해당 행 조건

array([10.5  , 12.875])

In [78]:
np.nan #숫자가 아님

nan

In [79]:
np.inf #무한대

inf

## 연산

In [81]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
a + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
np.arange(10) + np.arange(50,60)

array([50, 52, 54, 56, 58, 60, 62, 64, 66, 68])

In [84]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
b = np.arange(1,11)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
a+b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [88]:
a-b

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [89]:
a/b

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ,
       0.83333333, 0.85714286, 0.875     , 0.88888889, 0.9       ])